---
- name: Include distribution-specific tasks (if they exist)
  include_tasks: "{{ version_specific_task_file }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"  #  To hit exact distro + version:  E.g. Ubuntu-14.04.yml
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"   # To hit general family + major version: E.g: RedHat-6.yml will play for both Centos 6 and Red Hat 6
      skip: true
  loop_control:
    loop_var: version_specific_task_file

- name: Install xfonts (a prerequisite of wkhtmltopdf)
  package:
    name: "{{ xfonts_package_name }}"
    state: present
    update_cache: true

- name: Download wkhtmltopdf
  get_url:
   # These come from vars/{version}.yml
    url: "{{ package_source }}"
    dest: "{{ download_dest }}"
    checksum: "{{ package_checksum }}"

- name: Install wkhtmltopdf (Debian-ish)
  apt:
    deb: "{{ download_dest }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install wkhtmltopdf (Red-hat-ish)
  yum:
    name: "{{ download_dest }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'
